remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
windows_url: https://github.com/olehhhm/NoteerT/releases/latest/download/NoteerT.exe
macos_url: https://github.com/olehhhm/NoteerT/releases/latest/download/NoteerT.dmg
play_market_url: https://play.google.com/store/apps/details?id=com.mnk.noteert&pli=1
